[package]
name = "order-book"
version = "0.1.0"
edition = "2024"

[features]
default = []

[dependencies]
tracing.workspace = true
spsc = { path = "../spsc" }
logging = { path = "../logging" }
types = { path = "../types" }
utils = { path = "../utils" }
snapshot = { path = "../snapshot" }
crossbeam-channel.workspace = true
arc-swap = "1.9.1"
ahash = "0.8"

# Dev dependencies for testing
[dev-dependencies]
tracing-subscriber.workspace = true
criterion.workspace = true
hdrhistogram.workspace = true
crossbeam.workspace = true
core_affinity.workspace = true
lazy_static.workspace = true

[[bench]]
name = "ob_bench"
harness = false
path = "bench/bench.rs"

[[test]]
name = "perf_order_creation"
harness = false
path = "tests/perf/order_creation.rs"

[[test]]
name = "perf_order_deletion"
harness = false
path = "tests/perf/order_deletion.rs"

[[test]]
name = "perf_order_deletion_with_depth"
harness = false
path = "tests/perf/order_deletion_with_depth.rs"

[[test]]
name = "perf_order_deletion_same_price_depth"
harness = false
path = "tests/perf/order_deletion_same_price_depth.rs"

[profile.profiling]
inherits = "release"
debug = true
strip = false
